### ISSUE TITLE
Fixing Display Resolution w/ NVIDIA graphics support

### ISSUE THREAD

**Issue by dylan-gonzalez** [Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo#1]
Trying to add support for different display resolution options on the ENV200 ubuntu 22.04 installation

**Comment by dylan-gonzalez** [comment]
07-10-23

Me @AnthonyZhOon @jaimasters trying this: https://forums.linuxmint.com/viewtopic.php?t=278885#top

### So, trying x.org nouveau server with NVIDIA Driver as a Custom EDID.

On reboot of nouveau server, screen remains blank...
Rebootted a second time, this time we see the "OK" output of the kernel modules...

If we boot into recovery mode, then we can get into the OS.

We can follow the forum above, but realise that this will only solve resolution-related issues (e.g. not showing more than 1 display resolution option). We can try this (maybe don't need the custom EDID file as this is for integrating nvidia-driver support into the xorg server we believe??).

**Comment by hubdwoo** [comment]
# 14-12-23

I guess we can close this since the display resolution is fixed.
