### ISSUE TITLE
Lidar

### ISSUE THREAD

**Issue by hubdwoo** [Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo#2]
- [x] Find relevant drivers
- [x] Run the LiDAR

**Comment by hubdwoo** [comment]
# From Notion
***Velodyne vlp32 (Lidar)***

- https://github.com/ros-drivers/velodyne/tree/humble-devel
- LiDAR setup, able to ping data to and from the sensor (could hear the thing inside the lidar turning)
- Unable to visualize on RViz due to an error in the velodyne_pointcloud package



![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo/assets/36449214/e8e92348-f89c-4b82-970c-d50c79eef9a1)

**Comment by dylan-gonzalez** [comment]
Connected the Velodyne Driver box to the Teltonika Router
Reachable on 192.168.1.201

`sudo apt install ros-humble-velodyne`

The Velodyne LiDAR is VLP32C-B.
Run the driver which will publish raw packets, `/velodyne_packets`.
`ros2 launch velodyne_driver velodyne_driver_node-VLP32C-launch.py`

Run the transform-node which converts `/velodyne_packets` to `/velodyne_points`.
`ros2 launch velodyne_pointcloud velodyne_transform_node-VLP32C-launch.py`

To visualise in RVIZ, make sure to set your fixed frame to `/velodyne`.

![Image](https://github.com/Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo/assets/45161987/cfc568cd-ce60-4ca3-92fb-2660b3a3d6f9)

**Comment by dylan-gonzalez** [comment]
LiDAR currently does not turn on through the power management console since reflashing the ECU. Contacted Streetdrone about it.
