### ISSUE TITLE
Try using PopOS to fix the nvidia-drivers

### ISSUE THREAD

**Issue by hubdwoo** [Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo#9]
# 15-11-23
After having a meeting with Streetdrone turns out they currently aren't using the GPU at all. That means that they use BalenaOS without nvidia-drivers.

- [ ] Install PopOS on a partition on the ENV
- [ ] Test nvidia commands such as "nvidia-smi"

**Comment by klo40** [comment]
17/11/2023 Kendrick 
-Flashed PopOS to a USB drive, uploaded to the ENV computer.
-ENV responded with a bunch of terminal code, ended up completing/freezing after 2 minutes with no clear direction on what to do next
![popos fail](https://github.com/Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo/assets/142164040/fc64aeba-25b6-4361-ade4-02645b8ebeb6)

- According to the PopOs website, it should have gone into the desktop but it didn't https://support.system76.com/articles/live-disk/
- 
<img width="511" alt="popos desktop" src="https://github.com/Monash-Connected-Autonomous-Vehicle/ENV200-Shadow-Repo/assets/142164040/7b59cb1c-bc41-498c-8adb-c0860b915957">
- If need further description let me know.

**Comment by dylan-gonzalez** [comment]
I feel like we can't label this as 'PopOS not working' - we haven't yet tested whether the nvidia-drivers work or not
Maybe we can try booting on another PC?

**Comment by hubdwoo** [comment]
@dylan-gonzalez I'll test it out on the Hive 4 in ws 1

**Comment by hubdwoo** [comment]
@klo40 do you remember how long did you get stuck on that page?

**Comment by hubdwoo** [comment]
PopOS works without installing it. It has the nvidia-drivers in the installation section. Might test that out one more time to see if it works.

**Comment by klo40** [comment]
> @klo40 do you remember how long did you get stuck on that page?

I left it on there for at least 3 min before thinking it probably wasn't going to change state

**Comment by hubdwoo** [comment]
PopOS just froze for 10 mins. Don't think its possible to use em
